name: tests
on:
  push:
  pull_request:

jobs:
  tests_on_ubuntu_x86_64:
    name: Tests on Ubuntu (x86_64 and i686)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y gcc-multilib
    - name: run tests
      run: |
        make check

  tests_on_mac:
    name: Tests on MacOS (x86_64)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: run tests
      run: |
        sudo make check

  tests_on_windows:
    name: Tests on Windows (x64 and x86)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: x64 -> x64 tests on Windows
      shell: cmd
      run: |
        nmake -nologo -f Makefile.win32 check
        if %ERRORLEVEL% neq 0 exit /b %ERRORLEVEL%
        copy tests\test-prog.exe tests\test-prog-x64.exe 
        nmake -nologo -f Makefile.win32 clean
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: x86 -> x86 tests on Windows
      shell: cmd
      run: |
        nmake -nologo -f Makefile.win32 check
    - name: x64 -> x86 tests on Windows
      shell: cmd
      run: |
        cd tests && .\test-prog-x64.exe

  tests_on_alpine_x86_64:
    name: Tests on Alpine (x86_64 only)
    runs-on: ubuntu-latest
    container: alpine
    steps:
    - name: Install packages
      run: |
        apk add gcc musl-dev git make
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: run tests
      run: |
        make check
